# Configurations can be specific to Environment
# See, Example: in STG Environment, weight limit is provided as 10 Kgs and exception comments are  prepended with 'STG- '
# If The Environment variable - "ENV" is not exported on Server, Service default to 'DEV' configurations
DEV:
    packages:
        -   'type': 'Small'
            'length': 200
            'breadth': 300
            'height': 150   
            'cost': 5.00
        -   'type': Medium
            'length': 300
            'breadth': 400
            'height': 200
            'cost': 7.50
        -   'type': 'Large'
            'length': 400
            'breadth': 600
            'height': 250
            'cost': 8.50
    packageDimensionUnit: 'mm'
    packageCostUnit: '$'
    weightLimit:    
        'value': 25
        'unit': 'Kgs'
    ERROR_RESPONSES:
        typeError: 'Unexpected Input Detected'
        packageNotFound: 'Dimension(s) are not in expected range'
        weightException: 'Weight exceeded Limit {} {}'

STG:
    packages:
        -   'type': Medium
            'length': 300
            'breadth': 400
            'height': 200
            'cost': 7.50
        -   'type': 'Large'
            'length': 400
            'breadth': 600
            'height': 250
            'cost': 8.50
        -   'type': 'Small'
            'length': 200
            'breadth': 300
            'height': 150   
            'cost': 5.00
    packageDimensionUnit: 'mm'
    packageCostUnit: '$'
    weightLimit:    
        'value': 10
        'unit': 'Kgs'
    ERROR_RESPONSES:
        typeError: 'STG- Unexpected Input Detected'
        packageNotFound: 'STG- Dimension(s) are not in expected range'
        weightException: 'STG- Weight exceeded Limit {} {}'

PROD:
    packages:
        -   'type': Medium
            'length': 300
            'breadth': 400
            'height': 200
            'cost': 7.50
        -   'type': 'Large'
            'length': 400
            'breadth': 600
            'height': 250
            'cost': 8.50
        -   'type': 'Small'
            'length': 200
            'breadth': 300
            'height': 150   
            'cost': 5.00
    packageDimensionUnit: 'mm'
    packageCostUnit: '$'
    weightLimit:    
        'value': 25
        'unit': 'Kgs'
    ERROR_RESPONSES:
        typeError: 'Unexpected Input Detected'
        packageNotFound: 'Dimension(s) are not in expected range'
        weightException: 'Weight exceeded Limit {} {}'
