DEV:
    packages:
        -   'type': Medium
            'length': 300
            'breadth': 400
            'height': 200
            'cost': 7.50
        -   'type': 'Large'
            'length': 400
            'breadth': 600
            'height': 250
            'cost': 8.50
        -   'type': 'Small'
            'length': 200
            'breadth': 300
            'height': 150   
            'cost': 5.00
    packageDimensionUnit: 'mm'
    packageCostUnit: '$'
    weightLimit:    
        'value': 25
        'unit': 'Kgs'
    ERROR_RESPONSES:
        typeError: 'Unexpected Input Detected'
        packageNotFound: 'Dimension(s) are not in expected range'

STG:
    packages:
        -   'type': Medium
            'length': 300
            'breadth': 400
            'height': 200
            'cost': 7.50
        -   'type': 'Large'
            'length': 400
            'breadth': 600
            'height': 250
            'cost': 8.50
        -   'type': 'Small'
            'length': 200
            'breadth': 300
            'height': 150   
            'cost': 5.00
    packageDimensionUnit: 'mm'
    packageCostUnit: '$'
    weightLimit:    
        'value': 25
        'unit': 'Kgs'
    ERROR_RESPONSES:
        typeError: 'Unexpected Input Detected'
        packageNotFound: 'Dimension(s) are not in expected range'

PROD:
    packages:
        -   'type': Medium
            'length': 300
            'breadth': 400
            'height': 200
            'cost': 7.50
        -   'type': 'Large'
            'length': 400
            'breadth': 600
            'height': 250
            'cost': 8.50
        -   'type': 'Small'
            'length': 200
            'breadth': 300
            'height': 150   
            'cost': 5.00
    packageDimensionUnit: 'mm'
    packageCostUnit: '$'
    weightLimit:    
        'value': 25
        'unit': 'Kgs'
    ERROR_RESPONSES:
        typeError: 'Unexpected Input Detected'
        packageNotFound: 'Dimension(s) are not in expected range'